[build]
target-dir = "target"
artifact-dir = "./build/out"

[env]

# Constant VM properties
SYSTEM_PROPS_VM_SPECIFICATION_NAME = "Java Virtual Machine Specification"
SYSTEM_PROPS_VM_NAME = "SJVM"
SYSTEM_PROPS_VM_VENDOR = "Serial-ATA"